apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: actorconfig
spec:
  actor:
    idleTimeout: "30s"
    scanInterval: "10s"
    drainOngoingCallTimeout: "30s"
    drainRebalancedActors: true
    reentrancy:
      enabled: true
  dataPlane:
    # Configuraci贸n de los pipes de la aplicaci贸n (comunicaci贸n sidecar <-> sidecar)
    appPipes:
      # L铆mite de tiempo para la comunicaci贸n gRPC/HTTP saliente
      maxRequestBodySize: 4 # MB (default: 4)
      #  CLAVE: Reducir el timeout de las llamadas de service invocation
      readBufferSizeKB: 4 # KB (default: 4)
    http:
      readTimeout: "5s"
      writeTimeout: "5s"
      idleTimeout: "60s"
    grpc:
      connectionTimeout: "5s"
      maxRequestBodySize: 4
  nameResolution:
    component: "consul"
    version: "v1"
    configuration:
      selfRegister: true
  mtls:
    enabled: false